logging:
  level:
    com.netflix.discovery.TimedSupervisorTask: "OFF"
    org.springframework.security: DEBUG 

# app:
#   oauth2:
#     accessTokenUri: http://authen:9999/oauth/token
#     clientId: common-service
#     resourceId: common-service
#     secret: '{cipher}ec505f8be529a215962a0009bd94880a3bac8d9dc9d57c4b50f7a84ab22d4123f85e3bf567d3770f4175f140f032358c'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 5
     preferIpAddress: true
     instanceId: ${random.value}:${spring.application.name}:${server.port}
